config/routes.rb
Splurty::Application.routes.draw do

  root 'quotes#index'

  resources :quotes

  get 'about', :to => 'quotes#about'
end

app/models/quote.rb
class Quote < ActiveRecord::Base
	validates :saying, :presence => true, :length => { :maximum => 140, :minimum => 3 }
	validates :author, :presence => true, :length => { :maximum => 50, :minimum => 3}

	def unique_tag
    	abbr = self.author.split(" ").collect do |sub_string|
      	sub_string[0]
    	end
    	abbr.join + '#' + self.id.to_s
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		@quote = Quote.order("RANDOM()").first
	end

	def create
		@quote = Quote.create(quote_params)
		if @quote.invalid?
			flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
		end
		redirect_to root_path
	end	

	def about
	end

	def show
		@quote = Quote.where(:id => params[:id]).first
		if @quote.blank?
      	render :text => "Not Found", :status => :not_found
    	end
    end

	private

	def quote_params
		params.require(:quote).permit(:saying, :author)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Splurty</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--thanks for the tip, ken -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<header>
		
		<div class="col-xs-3">
			<%= link_to root_path, :class => 'logo' do %>
			<div class="circle">
			  <br />
			  Learn
			  <br />
			  to code
			  <br />
			  now
			</div>
			<% end %>
		</div>
		<div class="col-xs-4 hidden-xs slogan">
			Splurting out unsolicited advice about entrepreneurship since 2014.
		</div>
		<div class="col-xs-8 col-xs-offset-1 col-sm-offset-0 col-sm-5 links">
      	<!-- Button trigger modal -->
      	<%= link_to 'Contribute', '#', :data => {:toggle => 'modal', :target => '#myModal'} %>&nbsp;&nbsp;
      	<%= link_to 'About', about_path %>
		</div>

	</header>

	  <!-- Modal -->
	  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	    <div class="modal-dialog">
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	          <h4 class="modal-title" id="myModalLabel">Contribute your quote</h4>
	        </div>
	        <div class="modal-body">
	        <%= simple_form_for Quote.new do |f| %>
  			<%= f.input :saying, :label => "What is the saying you want to add?", :placeholder => "Fear is the disease. Hustle is the antidote." %>
  			<br />
  			<%= f.input :author, :label => "Who is the author of the quote?", :placeholder => 'Travis Kalanick' %>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	          <%= f.submit 'Create', :class => 'btn btn-danger' %>
	          <% end %>
	        </div>
	      </div>
	    </div>
	  </div>


	<hr />
	<br class="clear" />

	<div class="container">
	<% if flash[:error].present? %>
		<div class="col-xs-10 col-xs-offset-1 alert alert-danger">
			<%= flash[:error].html_safe %>
		</div>
	<% end %>	
	<%= yield %>
	</div>

	<div class="footer">
    <div class="container">
       <div class="col-xs-12 col-sm-6">
        <%= link_to "This isn't enough, I need more", root_path, :class => 'next-quote' %>
      	</div>
      	<div class="col-xs-12 col-sm-6 footer-blurb">
        Bootstrap's grid system is nice.<br />
        Want to build your own Splurty Web App - <a href="http://thefirehoseproject.com">Learn how to code here</a>
      </div>
    </div>
  	</div>

</body>
</html>

app/views/quotes/about.html.erb
<div class="col-xs-10 col-xs-offset-1 about">
  <h1>About Splurty</h1>

   <p>
    This version of Splurty was built by Mark. He is often at a loss for words. When this happens, he usually fires up a <a target="_blank" href="http://www.loremipsum.de/">lorem ipsum generator</a> and lets it do the talking for him. 
  </p>

  <br />
  <p>
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. 
  </p>

  <div class="col-xs-12 col-sm-4" style="padding-top:30px;">
    <%= image_tag 'mark.jpg', :class => 'img-responsive' %>
  </div>
  <div class="col-xs-12 col-sm-7 col-sm-offset-1">
    <h2 class="text-center">Mark</h2>
    <br />
    <p>
      Mark stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit ame. 
    </p>
  </div>

</div>


<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
  <span>SPLURTY / No. <%= @quote.id %></span>
  Here's the <u>best unsolicited startup advice</u> you can get!
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />

app/views/quotes/new.html.erb
<h1>Enter your quote details</h1>

<%= simple_form_for @quote do |f| %>
	<%= f.input :saying %>
	<%= f.input :author %>
	<br />
	<%= f.submit 'Create', :class => 'btn btn-danger' %>
<% end %>

app/views/quotes/show.html.erb
<h2>
  <span>SPLURTY / <%= @quote.unique_tag %></span>
  Here's the <u>best unsolicited startup advice</u> you can get!
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />